apiVersion: skaffold/v2alpha3
#apiVersion: skaffold/v4beta2
kind: Config
deploy: 
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local: 
    push: false
  #googleCloudBuild:
  #  projectId: project-herbaquoter-dev
  artifacts:
    #- image: cristiancasd/herbaquoter-auth-products
    #  context: auth-products
    #  docker:
    #    dockerfile: Dockerfile
    #  sync:
    #    manual:
    #      - src: "src/**/*.ts"
    #        dest: .
    #- image: cristiancasd/herbaquoter-quoters
    #  context: quoterss
    #  docker:
    #    dockerfile: Dockerfile
    #  sync:
    #    manual:
    #      - src: '**/*.js'
    #       dest: .
    - image: cristiancasd/herbaquoter-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
   