apiVersion: skaffold/v2alpha3
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: cristiancasd/herbaquoter-auth-products
      context: auth-products
      docker: 
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: "src/**/*.ts"
            dest: .
    - image: cristiancasd/herbaquoter-quoters
      context: quoterss
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .          
    - image: cristiancasd/herbaquoter-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
    
deploy:
  kubectl:
    manifests:
      - ./infra/k8s-dev/auth-products-depl.yaml
      - ./infra/k8s-dev/quoters-depl.yaml

      - ./infra/k8s/client-depl.yaml
      - ./infra/k8s/auth-products-postgres-depl.yaml
      - ./infra/k8s/quoters-postgres-depl.yaml
      - ./infra/k8s/ingress-srv.yaml

