version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports: 
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: herbaAP
    volumes:
      - ./postgres:/var/lib/postgresql/data

  db-test:
    image: postgres:14.3
    restart: always
    ports: 
      - "5436:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: herbaAP_test
    volumes:
      - ./postgres:/var/lib/postgresql/data
