apiVersion: apps/v1
kind: Deployment
metadata:
  name: quoters-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quoters
  template:
    metadata:
      labels:
        app: quoters
    spec: 
      containers:
        - name: quoters
          image: cristiancasd/herbaquoter-quoters  
          env:
#            - name: MONGO_URI
#              value: 'postgresdb://quoters-postgres-srv:5432/quoters'
            - name: DB_PASSWORD
              value: '1389!DJ12nddcsvcds@w1'

            - name: DB_NAME
              value: 'quoters-postgres'

            - name: DB_HOST
              value: 'quoters-postgres-srv'

            - name: DB_PORT
              value: '5432'

            - name: DB_USERNAME
              value: 'postgres'

            - name: JWT_SECRET
              value: 'passJWT3w125CriAHerb'

            - name: PORT
              value: '3010'

            - name: HOST_API
              value: 'http://localhost:3010/api'

            - name: STAGE
              value: 'dev'

            - name: AXIOS_URL_BACKEND_USERS_DEV
              value: 'http://auth-products-srv/api/auth/check-renew-token'
            

  
#            - name: JWT_KEY
#              valueFrom:
#                secretKeyRef:
#                  name: jwt-secret
#                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: quoters-srv
spec:
  selector:
    app: quoters
  ports:
    - name: quoters
      protocol: TCP
      port: 3010
      targetPort: 3010
