version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports: 
      - "5433:5432"
    environment:  
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: herbalifedbnode 
    volumes:
      - ./db/data/postgres:/var/lib/postgresql/data
      #- ./postgres:/var/lib/postgresql/data

  db-test:
    image: postgres:14.3
    restart: always
    ports: 
      - "5434:5432"
    environment: 
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME_TEST}
    container_name: herbalifedbnode_db
    volumes:
      - ./db/data-test/postgres:/var/lib/postgresql/data
