name: deploy-manifests
on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-cli@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Download kubeconfig.yaml
        run: |
          mkdir -p ~/.kube
          curl -o ~/.kube/config -L "https://raw.githubusercontent.com/your-repo/kubeconfig.yaml"
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
