name: tests-quoters

on: 
  pull_request:
    paths:
      - 'pruebas/**'  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd quoterss && npm install && npm run test:ci
