name: tests-quoters

on: 
  pull_request:
    paths:
      - 'quoterss/**'  

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - run: cd quoterss && npm install && npm run test:ci
        env:
          DB_USERNAME: postgres     #DB USER
          DB_HOST_TEST: localhost    #DB HOST
          DB_NAME_TEST: postgres #DB databaser
          DB_PASSWORD: postgres #DB password
          DB_PORT_TEST: 5432
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          CLOUDINARY_URL: ${{ secrets.CLOUDINARY_URL }}
