name: tests-auth-products

on: 
  pull_request:
    paths:
      - 'auth-products/**'  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth-products && npm install && npm run test:ci
